# Generated by Django 2.2.6 on 2020-05-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0004_remove_photographer_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='profile_img',
            field=models.ImageField(default='avatar.png', upload_to=''),
        ),
    ]
