# Generated by Django 2.2.6 on 2020-05-22 04:59

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0005_auto_20200521_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='profile_img',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
