# Generated by Django 2.2.6 on 2020-05-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20200522_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ManyToManyField(blank=True, to='photographers.Album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ManyToManyField(blank=True, to='photos.Category'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='photos.Tag'),
        ),
    ]
