# Generated by Django 2.2.6 on 2020-05-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20200522_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tags',
        ),
    ]
