# Generated by Django 2.2.6 on 2020-05-23 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_remove_category_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
