# Generated by Django 2.2.6 on 2020-05-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_img',
        ),
    ]
