# Generated by Django 2.2.6 on 2020-05-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20200526_1251'),
        ('customers', '0006_auto_20200526_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete='CASCADE', to='photos.Photo')),
                ('user', models.ForeignKey(on_delete='CASCADE', to='customers.Customer')),
            ],
        ),
    ]
